// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHT4xWnKarNNFpyIzvfF6wAE7bhnbfyMQ',
    appId: '1:699965936110:web:965a3c8df676b7ca54feff',
    messagingSenderId: '699965936110',
    projectId: 'gedikmobil',
    authDomain: 'gedikmobil.firebaseapp.com',
    storageBucket: 'gedikmobil.firebasestorage.app',
    measurementId: 'G-N9MFWSY4SL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACnI_bKrKWYXmvZKDgjx0R_8IeJGlvLck',
    appId: '1:699965936110:android:4e4a2b28377279bd54feff',
    messagingSenderId: '699965936110',
    projectId: 'gedikmobil',
    storageBucket: 'gedikmobil.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzgf5GQNYvYuyLVoGcRzhzSxXe9tqu37U',
    appId: '1:699965936110:ios:5f54c40f5f8e034754feff',
    messagingSenderId: '699965936110',
    projectId: 'gedikmobil',
    storageBucket: 'gedikmobil.firebasestorage.app',
    iosBundleId: 'com.example.gedikMobil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzgf5GQNYvYuyLVoGcRzhzSxXe9tqu37U',
    appId: '1:699965936110:ios:5f54c40f5f8e034754feff',
    messagingSenderId: '699965936110',
    projectId: 'gedikmobil',
    storageBucket: 'gedikmobil.firebasestorage.app',
    iosBundleId: 'com.example.gedikMobil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHT4xWnKarNNFpyIzvfF6wAE7bhnbfyMQ',
    appId: '1:699965936110:web:965a3c8df676b7ca54feff',
    messagingSenderId: '699965936110',
    projectId: 'gedikmobil',
    authDomain: 'gedikmobil.firebaseapp.com',
    storageBucket: 'gedikmobil.firebasestorage.app',
    measurementId: 'G-N9MFWSY4SL',
  );
}